version: '3.7'

services:
  client:
    image: tiagomartinho/ads-client
    depends_on:
      - server
    build:
      context: client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 6000:80
    networks:
      - ads

  server:
    image: tiagomartinho/ads-server
    build:
      context: server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 6001:8080
    networks:
      - ads

networks:
  ads: