name: Build Docker image

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build_client:
    name: Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_CR_USER }}
          password: ${{ secrets.DOCKER_CR_TOKEN }}
          registry: ghcr.io
          repository: sandrohc/ads-client
          tag_with_ref: true
          path: client/
  build_server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_CR_USER }}
          password: ${{ secrets.DOCKER_CR_TOKEN }}
          registry: ghcr.io
          repository: sandrohc/ads-server
          tag_with_ref: true
          path: server/